# Generated by Django 4.2.5 on 2023-10-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_options_product_users_whishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='users_whishlist',
            new_name='users_wishlist',
        ),
    ]
